server:
  port: 9527
spring:
  application:
    name: aigou-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes:
    plat.serviceId: aigou-plat #这是调用满足条件的服务名，注意要小写
    plat.path: /plat/** #这是所有路径前的通配
    product.serviceId: aigou-product #这是调用满足条件的服务名，注意要小写
    product.path: /product/** #这是所有路径前的通配
  ignored-services: "*"
  prefix: "/services"